--
-- PostgreSQL database dump
--

\restrict QUfHwaMGHbc99CWmEOVOhStkDT0lTEoVPgsuEYbK7CkzAc4fQjhjaleIFoygGgz

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.1 (Debian 18.1-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    audit_id integer NOT NULL,
    "timestamp" timestamp without time zone DEFAULT now() NOT NULL,
    trace_id character varying(255) DEFAULT gen_random_uuid(),
    ip_address character varying(255),
    system_username character varying(255),
    metadata character varying(255)
);


--
-- Name: audit_logs_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_logs_audit_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: audit_logs_audit_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_logs_audit_id_seq OWNED BY public.audit_logs.audit_id;


--
-- Name: audit_logs_audit_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN audit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_audit_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_logs_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: customer_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_accounts (
    account_id bigint NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    id_number character varying(255),
    email_address character varying(255),
    cellphone_number character varying(255)
);


--
-- Name: customer_accounts_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.customer_accounts_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: statements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.statements (
    statement_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    account_id bigint,
    filename character varying(255),
    retrieval_token character varying(255),
    link character varying(1000),
    expires_at timestamp without time zone
);


--
-- Name: statements_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.statements_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: statements_statement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.statements_statement_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: statements_statement_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.statements_statement_id_seq OWNED BY public.statements.statement_id;


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    transaction_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    post_date date NOT NULL,
    account_id bigint,
    amount numeric(38,2),
    description character varying(255),
    dr_or_cr character varying(255),
    CONSTRAINT transactions_dr_or_cr_check CHECK (((dr_or_cr)::text = ANY (ARRAY[('DR'::character varying)::text, ('CR'::character varying)::text])))
);


--
-- Name: transactions_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.transactions_transaction_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: transactions_transaction_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.transactions_transaction_id_seq OWNED BY public.transactions.transaction_id;


--
-- Name: statements statement_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.statements ALTER COLUMN statement_id SET DEFAULT nextval('public.statements_statement_id_seq'::regclass);


--
-- Name: transactions transaction_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions ALTER COLUMN transaction_id SET DEFAULT nextval('public.transactions_transaction_id_seq'::regclass);


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.audit_logs (audit_id, "timestamp", trace_id, ip_address, system_username, metadata) FROM stdin;
252	2026-02-03 15:30:59.862291	d150f0790812dcd267ed4834eb77e9e8	\N	\N	Transactions fetched by accountId: 1000000003
302	2026-02-03 15:33:17.183376	5d986aaf0566101bb72513722ce875ad	\N	\N	Transactions fetched by accountId: 1000000003
352	2026-02-03 15:38:07.052031	5dd27e4a22086f9ab09d1fbd157d6b04	\N	\N	Transactions fetched by accountId: 1000000003
402	2026-02-03 15:54:17.398581	d70fe924191c85fcaf1e5cdd84532172	\N	\N	Transactions fetched by accountId: 1000000003
452	2026-02-03 15:56:45.500587	148ce46502eb06ea09bca83632ef5e60	\N	\N	Transactions fetched by accountId: 1000000003
502	2026-02-03 15:58:46.164956	1aaf6b6b2f9318bbc07e3197853ff390	\N	\N	Transactions fetched by accountId: 1000000003
552	2026-02-03 16:17:56.348379	9fb8e2ce5bea1169b5879a3f43b6215d	0:0:0:0:0:0:0:1	\N	Transactions fetched by accountId: 1000000003
602	2026-02-03 16:20:03.755757	5aeaa97119cf88062034cf22596022fa	0:0:0:0:0:0:0:1	user	Transactions fetched by accountId: 1000000003
652	2026-02-03 17:31:19.98239	6404865d9acc08208f6ecfb715a8e6c3	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
702	2026-02-03 17:32:49.194694	24ecde046f495b5905f53a55226d394b	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
752	2026-02-03 17:36:00.27852	658be1ec2de6d5f1fdbf68a073b5bc02	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
802	2026-02-03 19:04:23.698956	35826c89a89e24c99da7ed91e6453766	0:0:0:0:0:0:0:1	user	Transaction created: 
803	2026-02-03 19:05:08.002344	e09e96cbf10ec3820e71091cc601ddf8	0:0:0:0:0:0:0:1	user	Transaction created: 
852	2026-02-03 19:26:18.348782	ba8f0e201d78a71f2d0fa4e9cc75cc62	0:0:0:0:0:0:0:1	user	Created Customer Account: 
902	2026-02-03 21:27:15.864643	694eafa323f5e84cce6994b1dafca994	0:0:0:0:0:0:0:1	user	New Statement generated: 
952	2026-02-03 21:56:21.879181	6e0ac7eaefe44704601108d820e305d4	0:0:0:0:0:0:0:1	user	PDF Statement generated: 
1002	2026-02-03 22:00:02.442048	9da526f8cee604ce4f4e88c294d0f06d	0:0:0:0:0:0:0:1	user	PDF Statement generated: 
1052	2026-02-03 22:05:06.066204	398467d5f028a85bac6e1c3e6d88b0d0	0:0:0:0:0:0:0:1	user	PDF Statement generated: 
1053	2026-02-03 22:05:06.390876	398467d5f028a85bac6e1c3e6d88b0d0	0:0:0:0:0:0:0:1	user	PDF uploaded: null
1054	2026-02-03 22:05:06.415515	398467d5f028a85bac6e1c3e6d88b0d0	0:0:0:0:0:0:0:1	user	Presigned Link generated: 86c6f62499354e86809ef6ae43098156.pdf
1102	2026-02-03 22:08:29.102925	8633674ffcbf17061a690244d04fbc6c	0:0:0:0:0:0:0:1	user	PDF Statement generated: 
1103	2026-02-03 22:08:29.431493	8633674ffcbf17061a690244d04fbc6c	0:0:0:0:0:0:0:1	user	PDF uploaded: null
1104	2026-02-03 22:08:29.456773	8633674ffcbf17061a690244d04fbc6c	0:0:0:0:0:0:0:1	user	Presigned Link generated: 1631f7895d484516903b19801ac2ca24.pdf
1105	2026-02-03 22:08:29.46848	8633674ffcbf17061a690244d04fbc6c	0:0:0:0:0:0:0:1	user	New Statement generated: 
1152	2026-02-03 22:10:27.178884	71d3df67e5364dfeac8fdeda5deca8c4	0:0:0:0:0:0:0:1	user	PDF Statement generated: 
1153	2026-02-03 22:10:27.518213	71d3df67e5364dfeac8fdeda5deca8c4	0:0:0:0:0:0:0:1	user	PDF uploaded: null
1154	2026-02-03 22:10:27.547365	71d3df67e5364dfeac8fdeda5deca8c4	0:0:0:0:0:0:0:1	user	Presigned Link generated: 80fbf2422fab4d27a37331dbc2f6b3f5.pdf
1155	2026-02-03 22:10:27.559951	71d3df67e5364dfeac8fdeda5deca8c4	0:0:0:0:0:0:0:1	user	New Statement generated: 
1202	2026-02-03 22:15:11.137411	ca9f38ebefc3a53b34c67aeab26b9d19	0:0:0:0:0:0:0:1	user	PDF Statement generated: 
1203	2026-02-03 22:15:11.51336	ca9f38ebefc3a53b34c67aeab26b9d19	0:0:0:0:0:0:0:1	user	PDF uploaded: null
1204	2026-02-03 22:15:11.542249	ca9f38ebefc3a53b34c67aeab26b9d19	0:0:0:0:0:0:0:1	user	Presigned Link generated: f2547954b02b441a9cd2a11be4fbffcc.pdf
1205	2026-02-03 22:15:11.554866	ca9f38ebefc3a53b34c67aeab26b9d19	0:0:0:0:0:0:0:1	user	New Statement generated: 
1252	2026-02-03 22:28:20.897469	8c71f6c3dc48e5f9bd4cd172481cda0e	0:0:0:0:0:0:0:1	user	PDF Statement generated: 
1253	2026-02-03 22:28:21.356714	8c71f6c3dc48e5f9bd4cd172481cda0e	0:0:0:0:0:0:0:1	user	PDF uploaded: null
1254	2026-02-03 22:28:21.401299	8c71f6c3dc48e5f9bd4cd172481cda0e	0:0:0:0:0:0:0:1	user	Presigned Link generated: c9a6e597a18b4b6b8e7ecd7fc671ff92.pdf
1255	2026-02-03 22:28:21.41504	8c71f6c3dc48e5f9bd4cd172481cda0e	0:0:0:0:0:0:0:1	user	New Statement generated: 
1302	2026-02-03 22:30:03.32178	e3783cd8b83705823aeee45bbc273751	0:0:0:0:0:0:0:1	user	PDF Statement generated: 
1303	2026-02-03 22:30:03.640701	e3783cd8b83705823aeee45bbc273751	0:0:0:0:0:0:0:1	user	PDF uploaded: null
1304	2026-02-03 22:30:03.671226	e3783cd8b83705823aeee45bbc273751	0:0:0:0:0:0:0:1	user	Presigned Link generated: d1b79b0381184197b1cd0b0b96ab1a20.pdf
1305	2026-02-03 22:30:03.682283	e3783cd8b83705823aeee45bbc273751	0:0:0:0:0:0:0:1	user	New Statement generated: 
1352	2026-02-04 13:46:28.073196	1bc73f027e3f1145203f63d2f1aa2ec8	0:0:0:0:0:0:0:1	user	PDF Statement generated: 
1353	2026-02-04 13:46:28.404841	1bc73f027e3f1145203f63d2f1aa2ec8	0:0:0:0:0:0:0:1	user	PDF uploaded: 
1354	2026-02-04 13:46:28.434256	1bc73f027e3f1145203f63d2f1aa2ec8	0:0:0:0:0:0:0:1	user	Presigned Link generated: 
1355	2026-02-04 13:46:28.447423	1bc73f027e3f1145203f63d2f1aa2ec8	0:0:0:0:0:0:0:1	user	New Statement generated: 
1402	2026-02-04 14:25:32.340155	eb914f71aacb7cbf7318b0ec8817c52d	0:0:0:0:0:0:0:1	user	PDF Statement generated: 
1403	2026-02-04 14:25:32.667209	eb914f71aacb7cbf7318b0ec8817c52d	0:0:0:0:0:0:0:1	user	PDF uploaded: 
1404	2026-02-04 14:25:32.691908	eb914f71aacb7cbf7318b0ec8817c52d	0:0:0:0:0:0:0:1	user	Presigned Link generated: 
1405	2026-02-04 14:25:32.703948	eb914f71aacb7cbf7318b0ec8817c52d	0:0:0:0:0:0:0:1	user	New Statement generated: 
1406	2026-02-04 14:25:35.819064	274052388bce37a1aac835c805e4ef7a	127.0.0.1	anonymousUser	Statement downloading using public link: 
1407	2026-02-04 14:27:34.688553	1ef3ea690fb21f024650ded44f31664c	0:0:0:0:0:0:0:1	anonymousUser	Statement downloading using public link: 
1452	2026-02-04 14:33:11.904118	da5e1c0cdd419ee0e87f9d60bd04e1b2	0:0:0:0:0:0:0:1	anonymousUser	Statement downloading using public link: 
1453	2026-02-04 14:33:29.130126	b9948c7046beee357d1445d91a7d918d	0:0:0:0:0:0:0:1	anonymousUser	Statement downloading using public link: 
1454	2026-02-04 14:33:40.719957	dea135fd2983659e2ad645047b33f388	0:0:0:0:0:0:0:1	anonymousUser	Statement downloading using public link: 
1502	2026-02-04 15:56:09.985923	e8c6f53073378e82b9e7c7927e56f5c2	0:0:0:0:0:0:0:1	anonymousUser	Statement downloading using public link: 
1503	2026-02-04 15:56:48.022685	451f4290824ec0cafdc918424341c5c0	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1504	2026-02-04 15:56:49.426135	003c2af90db2886006948c17677bf462	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1505	2026-02-04 15:56:50.602268	c0f30175a9ac34df7891899bfb999fa6	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1506	2026-02-04 15:56:51.746451	7e0491725616f49536e076fa1b7b5fdb	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1507	2026-02-04 15:56:52.952811	133b68202d21be0bf1266d65a8f3013a	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1508	2026-02-04 15:56:54.085144	c63174fe35430c6f1533c87f04e0a23e	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1509	2026-02-04 15:56:55.305398	3523f6cd6adc5e3c834836ffc2113619	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1510	2026-02-04 15:56:56.42567	67858db63724e19dedd3303a5129d759	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1511	2026-02-04 15:56:57.472016	7450c2d65185d5d9448cc97b75fc24d5	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1512	2026-02-04 15:56:58.757014	dceea59cbceb244b69e02f8fccfe95ff	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1513	2026-02-04 15:56:59.995737	6b2356d527022dc10fe620c82ea97d5d	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1514	2026-02-04 15:57:01.229085	370916c50ee446d9105e5297d2fb3ce9	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1515	2026-02-04 15:57:10.200494	c94e4130463eff592a699bee355b659c	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1516	2026-02-04 15:57:12.803164	c1ede37aee014632688d404332fceded	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1517	2026-02-04 15:57:22.304145	9e56ba078817294d9c0265643bf902a8	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1518	2026-02-04 15:57:24.873919	2d1ec7b21d0494e77738dc4a0269031e	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1552	2026-02-04 16:31:09.070984	a6d4574370d5f7bd1056c219d6a37cb5	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1553	2026-02-04 16:31:10.699242	e83391dd2cbe36d897832dfee69f503c	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1554	2026-02-04 16:31:12.11225	4e0995c1d01da7d8ad594f0bc008f3ac	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1555	2026-02-04 16:31:13.42483	3cb28fb2bdf4837ae44d7aa3c8f65afb	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1556	2026-02-04 16:31:14.708583	88421203dd71824cd074221ab6e991b8	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1557	2026-02-04 16:31:15.858605	d5711aabe0e8735195069b3a682e557c	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1558	2026-02-04 16:31:17.076711	1890687177c3d2066161a5b1f66399d6	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1559	2026-02-04 16:31:18.380624	18943dbe2f78c707fbbcf6ffc6c03c5e	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1560	2026-02-04 16:31:19.456209	b68d9d8fed835542176e0d681f2f01c3	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1561	2026-02-04 16:31:20.626513	7543293c43038008a2003e75ddc46f76	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1562	2026-02-04 16:31:21.762432	65422502319bec9c26c8474a85592690	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1563	2026-02-04 16:31:22.86665	855b6e94af0f24d0abc3cf7f383b5b95	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1602	2026-02-04 16:42:14.40105	6353025516e5f0900382febc926af8e5	0:0:0:0:0:0:0:1	user	Transaction fetched by transactionId: 5
1652	2026-02-04 17:33:51.78438	555f5d1d473414a0ca34232da1b80d9e	0:0:0:0:0:0:0:1	postmanuser	Transaction fetched by transactionId: 5
1702	2026-02-04 17:35:51.048577	9f1ee16677fc310eaf943e7a2f517442	0:0:0:0:0:0:0:1	postmanuser	Transaction fetched by transactionId: 5
1752	2026-02-04 17:57:36.999314	8f63c47bfb4fb6ce5ed20368da6ad02a	0:0:0:0:0:0:0:1	postmanuser	Transactions fetched by accountId: 1
1753	2026-02-04 17:58:09.811915	3843da00e2684615a4e25e8e25d7f7db	0:0:0:0:0:0:0:1	postmanuser	Transactions fetched by accountId: 1000000003
1754	2026-02-04 18:16:34.580853	8e8d84852987d3ee771dff3ef27fd5f1	0:0:0:0:0:0:0:1	postmanuser	Transactions fetched by accountId: 1000000003
1755	2026-02-04 18:16:43.901412	e73de0b0e42b00b5ee2ca2df47f5ad30	0:0:0:0:0:0:0:1	postmanuser	Transaction fetched by transactionId: 5
1756	2026-02-04 18:17:07.275017	3f4811e8f19c8e8b75e51907894eedfb	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
1757	2026-02-04 18:17:07.653136	3f4811e8f19c8e8b75e51907894eedfb	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
1758	2026-02-04 18:17:07.68055	3f4811e8f19c8e8b75e51907894eedfb	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
1759	2026-02-04 18:17:07.69234	3f4811e8f19c8e8b75e51907894eedfb	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
1760	2026-02-04 18:17:50.270001	b27b6e9b160b3694b8aedfb663a12203	127.0.0.1	anonymousUser	Statement downloading using public link: 
1761	2026-02-05 08:53:33.035908	4d7ea430b46b1a7d2a254f9a69fd4e83	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
1762	2026-02-05 08:53:33.056904	4d7ea430b46b1a7d2a254f9a69fd4e83	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
1763	2026-02-05 08:53:33.064038	4d7ea430b46b1a7d2a254f9a69fd4e83	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
1764	2026-02-05 08:53:33.07406	4d7ea430b46b1a7d2a254f9a69fd4e83	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
1802	2026-02-05 08:58:34.301066	feb9aa50f9c0df8004846e8eed664327	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
1803	2026-02-05 08:58:34.600601	feb9aa50f9c0df8004846e8eed664327	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
1804	2026-02-05 08:58:34.62408	feb9aa50f9c0df8004846e8eed664327	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
1805	2026-02-05 08:58:34.634563	feb9aa50f9c0df8004846e8eed664327	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
1852	2026-02-05 09:00:10.235596	1e66eb9c890af1b4a7c4fca6ad1d2002	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
1853	2026-02-05 09:00:10.560327	1e66eb9c890af1b4a7c4fca6ad1d2002	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
1854	2026-02-05 09:00:10.591819	1e66eb9c890af1b4a7c4fca6ad1d2002	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
1855	2026-02-05 09:00:10.603291	1e66eb9c890af1b4a7c4fca6ad1d2002	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
1902	2026-02-05 09:02:58.310901	888877c3e042a5235ab9d78522ad4fc7	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
1903	2026-02-05 09:02:58.655588	888877c3e042a5235ab9d78522ad4fc7	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
1904	2026-02-05 09:02:58.681786	888877c3e042a5235ab9d78522ad4fc7	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
1905	2026-02-05 09:02:58.69213	888877c3e042a5235ab9d78522ad4fc7	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
1952	2026-02-05 09:04:00.007697	d97463d99ea0d75b63e7cd94437dc7e8	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
1953	2026-02-05 09:04:00.341376	d97463d99ea0d75b63e7cd94437dc7e8	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
1954	2026-02-05 09:04:00.364982	d97463d99ea0d75b63e7cd94437dc7e8	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
1955	2026-02-05 09:04:00.376454	d97463d99ea0d75b63e7cd94437dc7e8	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
1956	2026-02-05 09:04:02.253055	ef6d96a5395f129aa96349885851d702	127.0.0.1	anonymousUser	Statement downloading using public link: 
1957	2026-02-05 09:04:46.193038	1c2c96bdf3b87e9371f366985abf8d2f	0:0:0:0:0:0:0:1	anonymousUser	Statement downloading using public link: 
2002	2026-02-05 09:07:27.827884	f80be4b076f5205e24433649a1dfae67	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2003	2026-02-05 09:07:28.146722	f80be4b076f5205e24433649a1dfae67	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2004	2026-02-05 09:07:28.170044	f80be4b076f5205e24433649a1dfae67	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2005	2026-02-05 09:07:28.180291	f80be4b076f5205e24433649a1dfae67	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2052	2026-02-05 10:05:23.360722	6d0870a20def2cb441c07729a9f59db5	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2053	2026-02-05 10:05:23.664337	6d0870a20def2cb441c07729a9f59db5	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2054	2026-02-05 10:05:23.692063	6d0870a20def2cb441c07729a9f59db5	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2055	2026-02-05 10:05:23.703095	6d0870a20def2cb441c07729a9f59db5	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2056	2026-02-05 10:05:26.320687	daf8220dcab5b97947ebcc23def62439	127.0.0.1	anonymousUser	Statement downloading using public link: 
2102	2026-02-05 12:11:30.754794	729f9ef1cb43e4ff2bb436d02a114113	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2103	2026-02-05 12:11:31.163088	729f9ef1cb43e4ff2bb436d02a114113	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2104	2026-02-05 12:11:31.197647	729f9ef1cb43e4ff2bb436d02a114113	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2105	2026-02-05 12:11:31.209234	729f9ef1cb43e4ff2bb436d02a114113	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2106	2026-02-05 12:11:34.102184	43fe79c21d14be69cd13978f25378b2b	127.0.0.1	anonymousUser	Statement downloading using public link: 
2152	2026-02-05 12:16:48.293864	2c2279e0ea08100861f76a281a91cbd9	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2153	2026-02-05 12:16:48.64488	2c2279e0ea08100861f76a281a91cbd9	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2154	2026-02-05 12:16:48.679207	2c2279e0ea08100861f76a281a91cbd9	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2155	2026-02-05 12:16:48.69319	2c2279e0ea08100861f76a281a91cbd9	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2156	2026-02-05 12:16:50.880553	6d277e91bd0379ff563400840cf38dff	127.0.0.1	anonymousUser	Statement downloading using public link: 
2202	2026-02-05 12:20:16.939093	48f022479ae8a98408c7ca05e26525f3	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2203	2026-02-05 12:20:17.279978	48f022479ae8a98408c7ca05e26525f3	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2204	2026-02-05 12:20:17.314382	48f022479ae8a98408c7ca05e26525f3	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2205	2026-02-05 12:20:17.336603	48f022479ae8a98408c7ca05e26525f3	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2206	2026-02-05 12:20:22.74692	7d0e73e68169f34e3c1f408ddbded2ae	127.0.0.1	anonymousUser	Statement downloading using public link: 
2252	2026-02-05 12:23:36.402041	fa13537256eb8e34176bc6ce399b2bb2	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2253	2026-02-05 12:23:36.807135	fa13537256eb8e34176bc6ce399b2bb2	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2254	2026-02-05 12:23:36.83856	fa13537256eb8e34176bc6ce399b2bb2	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2255	2026-02-05 12:23:36.888408	fa13537256eb8e34176bc6ce399b2bb2	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2256	2026-02-05 12:23:39.097826	fec5afd954b08dd3cac8412ad0db66e7	127.0.0.1	anonymousUser	Statement downloading using public link: 
2302	2026-02-05 12:29:13.441134	781622b9e5719d1722fc2d7338012175	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2303	2026-02-05 12:29:13.754544	781622b9e5719d1722fc2d7338012175	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2304	2026-02-05 12:29:13.778967	781622b9e5719d1722fc2d7338012175	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2305	2026-02-05 12:29:13.797917	781622b9e5719d1722fc2d7338012175	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2306	2026-02-05 12:29:18.291447	b8b9bb9892d2d5dcc0cad99feb3d75a0	127.0.0.1	anonymousUser	Statement downloading using public link: 
2352	2026-02-05 12:34:35.268838	66273a488e1ea91f65932b41c0b3ff27	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2353	2026-02-05 12:34:35.572052	66273a488e1ea91f65932b41c0b3ff27	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2354	2026-02-05 12:34:35.597578	66273a488e1ea91f65932b41c0b3ff27	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2355	2026-02-05 12:34:35.617254	66273a488e1ea91f65932b41c0b3ff27	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2356	2026-02-05 12:34:38.829398	4b5467bd22ad5a362b275bc34febce50	127.0.0.1	anonymousUser	Statement downloading using public link: 
2357	2026-02-05 12:46:08.035811	a2c8795ac2b3451334ad9f290bfb1084	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2358	2026-02-05 12:46:08.053328	a2c8795ac2b3451334ad9f290bfb1084	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2359	2026-02-05 12:46:08.05947	a2c8795ac2b3451334ad9f290bfb1084	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2360	2026-02-05 12:46:08.066688	a2c8795ac2b3451334ad9f290bfb1084	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2402	2026-02-05 14:24:44.879501	9eed8326d2ca1be45aa7a64db6386644	0:0:0:0:0:0:0:1	postmanuser	Transaction fetched by transactionId: 5
2403	2026-02-05 14:24:56.455159	3401f56c76fb26587234630c9060efe4	0:0:0:0:0:0:0:1	postmanuser	Transactions fetched by accountId: 1000000003
2404	2026-02-05 14:25:09.104199	ea56341663ea94c62f91a27c9df36678	0:0:0:0:0:0:0:1	postmanuser	Transaction created: 
2405	2026-02-05 14:27:47.622737	35bd03c09174a237d1fcde1cf8fbe5cf	0:0:0:0:0:0:0:1	postmanuser	Created Customer Account: 
2452	2026-02-05 15:05:02.352034	d97412bc9ed84ab20478a8a5baad3aa0	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2453	2026-02-05 15:05:02.695439	d97412bc9ed84ab20478a8a5baad3aa0	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2454	2026-02-05 15:05:02.73981	d97412bc9ed84ab20478a8a5baad3aa0	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2455	2026-02-05 15:05:02.767005	d97412bc9ed84ab20478a8a5baad3aa0	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2456	2026-02-05 15:05:05.805058	2546c3218ece6562dddf99f7d04f10b6	127.0.0.1	anonymousUser	Statement downloading using public link: 
2502	2026-02-05 15:13:40.518029	95cdf4b8f73d1507f14d8e8aeec5aa8b	0:0:0:0:0:0:0:1	postmanuser	PDF Statement generated: 
2503	2026-02-05 15:13:40.814389	95cdf4b8f73d1507f14d8e8aeec5aa8b	0:0:0:0:0:0:0:1	postmanuser	PDF uploaded: 
2504	2026-02-05 15:13:40.837696	95cdf4b8f73d1507f14d8e8aeec5aa8b	0:0:0:0:0:0:0:1	postmanuser	Presigned Link generated: 
2505	2026-02-05 15:13:40.870356	95cdf4b8f73d1507f14d8e8aeec5aa8b	0:0:0:0:0:0:0:1	postmanuser	New Statement generated: 
2552	2026-02-05 15:43:54.39806	2b85c3d10fba4b53c584b52fc6305f47	127.0.0.1	admin	PDF Statement generated: 
2553	2026-02-05 15:43:54.745927	2b85c3d10fba4b53c584b52fc6305f47	127.0.0.1	admin	PDF uploaded: 
2554	2026-02-05 15:43:54.770867	2b85c3d10fba4b53c584b52fc6305f47	127.0.0.1	admin	Presigned Link generated: 
2555	2026-02-05 15:43:54.797634	2b85c3d10fba4b53c584b52fc6305f47	127.0.0.1	admin	New Statement generated: 
2602	2026-02-05 17:08:31.947095	6adb772a2b21f844230301025204b979	127.0.0.1	user	Created Customer Account: 
2652	2026-02-05 17:09:43.41763	6adb6b5201b7fa0c3569f93c652f4645	127.0.0.1	user	Created Customer Account: 
2702	2026-02-05 17:10:40.250352	8771971f01d3c84346a931e89ad01b46	127.0.0.1	user	Created Customer Account: 
2752	2026-02-05 17:15:17.403373	7fba7037df3fcc994b90850e45b2b28e	127.0.0.1	user	Transactions fetched by accountId: 1000000001
2802	2026-02-05 18:09:00.050353	4cd9458b775a3a61554ecec5db576d2e	127.0.0.1	admin	PDF Statement generated: 
2803	2026-02-05 18:09:00.426829	4cd9458b775a3a61554ecec5db576d2e	127.0.0.1	admin	PDF uploaded: 
2804	2026-02-05 18:09:00.451896	4cd9458b775a3a61554ecec5db576d2e	127.0.0.1	admin	Presigned Link generated: 
2805	2026-02-05 18:09:00.475828	4cd9458b775a3a61554ecec5db576d2e	127.0.0.1	admin	New Statement generated: 
2806	2026-02-05 18:09:01.121293	624134f69fcadaf594cd5e87a20d5f39	127.0.0.1	user	Transactions fetched by accountId: 1000000001
2807	2026-02-05 18:09:01.266773	1002915f815ae814348e29c2f5bccabf	127.0.0.1	user	Created Customer Account: 
2852	2026-02-05 21:02:22.26707	6a307aa4311b6a78da8cb88d4806efd7	127.0.0.1	admin	PDF Statement generated: 
2853	2026-02-05 21:02:22.629289	6a307aa4311b6a78da8cb88d4806efd7	127.0.0.1	admin	PDF uploaded: 
2854	2026-02-05 21:02:22.671732	6a307aa4311b6a78da8cb88d4806efd7	127.0.0.1	admin	Presigned Link generated: 
2855	2026-02-05 21:02:22.706358	6a307aa4311b6a78da8cb88d4806efd7	127.0.0.1	admin	New Statement generated: 
2856	2026-02-05 21:02:23.350804	321ca568cf830579d46d754d73c114ed	127.0.0.1	user	Transactions fetched by accountId: 1000000001
2857	2026-02-05 21:02:23.486829	44b96907f6cc557d249e33eccd8b3893	127.0.0.1	user	Created Customer Account: 
2902	2026-02-05 21:03:28.175522	ebd747aebfdb2694517cd4c05e43983d	127.0.0.1	admin	PDF Statement generated: 
2903	2026-02-05 21:03:28.480564	ebd747aebfdb2694517cd4c05e43983d	127.0.0.1	admin	PDF uploaded: 
2904	2026-02-05 21:03:28.5063	ebd747aebfdb2694517cd4c05e43983d	127.0.0.1	admin	Presigned Link generated: 
2905	2026-02-05 21:03:28.521789	ebd747aebfdb2694517cd4c05e43983d	127.0.0.1	admin	New Statement generated: 
2906	2026-02-05 21:03:29.071957	079c2f74661cf5e87f186635914ba76b	127.0.0.1	user	Transactions fetched by accountId: 1000000001
2907	2026-02-05 21:03:29.187804	80a4dbf282b5ba0fce277d5538add5ea	127.0.0.1	user	Created Customer Account: 
2952	2026-02-05 21:03:55.315318	d23ff5846e6704f8ad2d6318be7e830c	127.0.0.1	admin	PDF Statement generated: 
2953	2026-02-05 21:03:55.687299	d23ff5846e6704f8ad2d6318be7e830c	127.0.0.1	admin	PDF uploaded: 
2954	2026-02-05 21:03:55.723096	d23ff5846e6704f8ad2d6318be7e830c	127.0.0.1	admin	Presigned Link generated: 
2955	2026-02-05 21:03:55.740864	d23ff5846e6704f8ad2d6318be7e830c	127.0.0.1	admin	New Statement generated: 
2956	2026-02-05 21:03:56.475632	33444cf9913589279dda8a5b95016647	127.0.0.1	user	Transactions fetched by accountId: 1000000001
2957	2026-02-05 21:03:56.628112	1db524e8bffb8ebf5be06aa52e90dc7b	127.0.0.1	user	Created Customer Account: 
\.


--
-- Data for Name: customer_accounts; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.customer_accounts (account_id, first_name, last_name, id_number, email_address, cellphone_number) FROM stdin;
1000000003	Alice	Johnson	9001010000085	alice.johnson@cbank.co.za	0821234569
1000000001	John	Doe	9001010000083	john.doe@cbank.co.za	0821234567
1000000002	Jane	Smith	9001010000084	jane.smith@cbank.co.za	0821234568
1000000010	Bob	Dylan	9001010000090	bob.dylan@cbank.co.za	0821234570
1000000011	Sarah	Parker	9001010000091	sarah.parker@cbank.co.za	0821234571
12345	Sarah	McTesty	90010100000010	sarah.mctesty@cbank.co.za	0712345678
\.


--
-- Data for Name: statements; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.statements (statement_id, created_at, account_id, filename, retrieval_token, link, expires_at) FROM stdin;
1302	2026-02-03 22:08:29.459446	1000000003	1631f7895d484516903b19801ac2ca24.pdf	6b0d607e-ff22-4c56-b149-f586e528977c	http://localhost:9000/files/1631f7895d484516903b19801ac2ca24.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260203T200829Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260203%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=341af57143d83ac7bae20710349c6ca01706a3b2464cf43e8488b2d399afe588	2026-02-03 22:38:29.459422
1352	2026-02-03 22:10:27.549984	1000000003	80fbf2422fab4d27a37331dbc2f6b3f5.pdf	1a6bb2a8-b55c-4485-a0a8-be716b3fba80	http://localhost:9000/files/80fbf2422fab4d27a37331dbc2f6b3f5.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260203T201027Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260203%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=fe48c20486f0dcb9d49c7c7ba22dc6dac8311d760f485cd8d6e9fb8939d91965	2026-02-03 22:40:27.549962
1402	2026-02-03 22:15:11.545289	1000000003	f2547954b02b441a9cd2a11be4fbffcc.pdf	1288efb9-1f17-4745-a594-f247f01bc576	http://localhost:9000/files/f2547954b02b441a9cd2a11be4fbffcc.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260203T201511Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260203%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=e7a135cbb0d237e4f00d6b149597e2ca8e62593b57e26d0c86ae605333aaf2ee	2026-02-03 22:45:11.545254
1452	2026-02-03 22:28:21.404826	1000000003	c9a6e597a18b4b6b8e7ecd7fc671ff92.pdf	53fcba79-e78b-46a1-8a49-5282bb6cf97e	http://localhost:9000/files/c9a6e597a18b4b6b8e7ecd7fc671ff92.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260203T202821Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260203%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=4f42cebb0a37c068edf5de407978f9fd496be321808a3af05bf73a415f6245c8	2026-02-03 22:58:21.404791
1502	2026-02-03 22:30:03.674179	1000000003	d1b79b0381184197b1cd0b0b96ab1a20.pdf	d580dfb8-7732-4a27-a75d-63f96e9e9372	http://localhost:9000/files/d1b79b0381184197b1cd0b0b96ab1a20.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260203T203003Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260203%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=58f06d99e7267a7d7beeb0d8c33bea209eaab449628b6eaa12cf4d8855627594	2026-02-03 23:00:03.674156
1552	2026-02-04 13:46:28.437171	1000000003	e2caf7188eaf488385f800a976335180.pdf	3afdad29-907a-41ed-b670-7ebdbe3d0914	http://localhost:9000/files/e2caf7188eaf488385f800a976335180.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260204T114628Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260204%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=9c897bd570988166dfcfa05f4bdf12a5055af7007a6fb1705412f3a71f7f89e2	2026-02-04 14:16:28.437146
1602	2026-02-04 14:25:32.695053	1000000003	167ca490fc994181bed87d5904aa72f5.pdf	28b4cfd7-2ebe-488c-bebb-cbb202b667a2	http://localhost:9000/files/167ca490fc994181bed87d5904aa72f5.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260204T122532Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260204%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=4b6c060b1da17c7ff936c82cda7f55fc0838c6aca1dc958dbb8d613c2b0f0500	2026-02-04 14:55:32.695019
1652	2026-02-04 18:17:07.683117	1000000003	4f947460d71349fe9bd7084f8ecba954.pdf	7af66b5e-eeb2-42fe-88fc-50ea96961b66	http://localhost:9000/files/4f947460d71349fe9bd7084f8ecba954.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260204T161707Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260204%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=a886bdf63a24ee50a954de5ad660e86e0c9cfd59aa0721231f3f17d13f5226c4	2026-02-04 18:47:07.683082
1653	2026-02-05 08:53:33.067516	1000000003	d8fb8b0e05af48fea9c154ae8e6bcb6f.pdf	da78ba38-89d9-41dc-9ed1-baea3af364f5	http://localhost:9000/files/d8fb8b0e05af48fea9c154ae8e6bcb6f.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T065333Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=3b0ebb987164a8de67471fc42aee22d79614d142b2bd8f996c21478653ad4f13	2026-02-05 09:23:33.0675
1702	2026-02-05 08:58:34.626323	1000000003	d432f124c7864c76954b6202282c762a.pdf	67e4320b-dff6-4f6e-881e-a0308cab84df	http://localhost:9000/files/d432f124c7864c76954b6202282c762a.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T065834Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=9be3a9b320f32ed7506679196728d982b47775a62d2f4c11899d7e22ec957394	2026-02-05 09:28:34.626299
1752	2026-02-05 09:00:10.594441	1000000003	a203ced4606b4f8ca50db2a232d73994.pdf	ef349794-ade7-43df-a0c8-7366ca15d01a	http://localhost:9000/files/a203ced4606b4f8ca50db2a232d73994.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T070010Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=8839d9d8fc59a63cf32231d8fe52a74656fd031e3c1b315edb1cf61f9d51d231	2026-02-05 09:30:10.594418
1802	2026-02-05 09:02:58.684565	1000000003	876141c746ac4fe5b44965c2bf170f91.pdf	696a27f6-91fd-4020-87de-962963e47390	http://localhost:9000/files/876141c746ac4fe5b44965c2bf170f91.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T070258Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=85ba8137744def59f5a2b64ef43dcc1abbedff346ec0bf1bdd3b1da2772c9703	2026-02-05 09:32:58.684532
1852	2026-02-05 09:04:00.367541	1000000003	17191df43e324a3faedeeb9dc17e8ee3.pdf	eca136d6-9075-4c32-8dd3-3285e2e59ea1	http://localhost:9000/files/17191df43e324a3faedeeb9dc17e8ee3.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T070400Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=6063089639385dd0787ea4c6535cc953f2f0421bd3ba2cf5a81fd81c2605f8b7	2026-02-05 09:34:00.367518
1902	2026-02-05 09:07:28.172711	1000000003	b9a238a6b53840b385f65ff4631f6c85.pdf	aa45eb3a-cf89-45e7-a03b-98b120fb1ad4	http://localhost:9000/files/b9a238a6b53840b385f65ff4631f6c85.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T070728Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=f58533c4e845c006832df2a9ae492012115db9960a77320a5852d02c62283bac	2026-02-05 09:37:28.172687
1952	2026-02-05 10:05:23.694934	1000000003	2a43372275a841bb8d4f6d4bda182cca.pdf	dba1045b-71ee-4c4e-860d-7e9c431ce83f	http://localhost:9000/files/2a43372275a841bb8d4f6d4bda182cca.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T080523Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=3807eaea76572e4b65826d06216be3bc54b38c5e470f00c236488ce10ae271fc	2026-02-05 10:35:23.69491
2002	2026-02-05 12:11:31.200941	1000000003	1b9957d240114e4981778577e36775bc.pdf	036c722e-4f41-4a19-8a1f-992fcfe877bb	http://localhost:9000/files/1b9957d240114e4981778577e36775bc.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T101131Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=7b67fce9e7ecd2ac85d38414303a14bbaf874a566415efe0b4a27867a053284e	2026-02-05 12:41:31.200915
2052	2026-02-05 12:16:48.682197	1000000003	9cec4aa0bd164a578755e384a811c029.pdf	c91f49e8-4113-4c17-99bf-985e0a34ceee	http://localhost:9000/files/9cec4aa0bd164a578755e384a811c029.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T101648Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=a3288b8dcbb758877297b455a943a8a869a505429e9636af72e735cae7017d73	2026-02-05 12:46:48.682126
4	2026-02-05 12:20:17.318741	1000000003	90716ade9c6f4b78b2c45827c717686e.pdf	26639c24-15f4-40b4-92b8-160534821129	http://localhost:9000/files/90716ade9c6f4b78b2c45827c717686e.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T102017Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=8f5ce6c4109e2fe01c7178b396bba2a227a611d5f3538291f1d85ac920ab2368	2026-02-05 12:50:17.316709
5	2026-02-05 12:23:36.843408	1000000003	86f84716eb5441cfad86f080b1dfdeaa.pdf	39950c86-0515-4523-8396-f62521b1e554	http://localhost:9000/files/86f84716eb5441cfad86f080b1dfdeaa.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T102336Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=18a114fb7f77d81a6dd635216565cb1bb356e24f58536e1a7aa80bfcdb0fa14b	2026-02-05 12:53:36.841443
6	2026-02-05 12:29:13.782841	1000000003	9e255d1ed9e94138911d16e9b88a360e.pdf	a3702cb4-d11c-444b-8bc0-b452fcf1758f	http://localhost:9000/files/9e255d1ed9e94138911d16e9b88a360e.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T102913Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=220c8239f2c8a13be72aa2e90f2c5d3003829afd9f83924fa75716e79ea863c3	2026-02-05 12:59:13.781107
7	2026-02-05 12:34:35.602019	1000000003	ea747af66be44ca482a8b299a6a80f93.pdf	7ff23066-8737-429a-9de1-a153b2c102b4	http://localhost:9000/files/ea747af66be44ca482a8b299a6a80f93.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T103435Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=4ecbaec2881388ded88a180705eb044fbae3d7a894be3f3d6271f492c516664a	2026-02-05 13:04:35.600374
8	2026-02-05 12:46:08.062435	1000000003	64d2ffed55f4421a98cad39f0fbfcaf0.pdf	aa2bde98-9d10-4e8e-ad9b-bfb92f713f4c	http://localhost:9000/files/64d2ffed55f4421a98cad39f0fbfcaf0.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T104608Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=c040fcbed61e95bada749c71989950654fa3d459611da30fbdbe5920542acd75	2026-02-05 13:16:08.061683
9	2026-02-05 15:05:02.752382	1000000003	e5999133ac6f49cab397109ceadfae60.pdf	58811035-7a59-43fd-a743-f028e11e1ce3	http://localhost:9000/files/e5999133ac6f49cab397109ceadfae60.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T130502Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=9a0a8f0654e004bae8d09c7dfa2babb558370586daf9e61ad9f67a67b9959295	2026-02-05 15:35:02.742458
10	2026-02-05 15:13:40.847769	1000000003	6000eed4e00140d989eefbd0aaec84ff.pdf	9737802f-96ed-4d32-a169-a6ba597968a4	http://localhost:9000/files/6000eed4e00140d989eefbd0aaec84ff.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T131340Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=7857ec496f2fb5c08eb49db86b91d87425573dcdf6a0b3eec7d5d65d6313c989	2026-02-05 15:43:40.840437
11	2026-02-05 15:43:54.783193	1000000003	49a26347453d40b1a9bcb4939f259828.pdf	f1740c41-3e54-42da-ab17-dac791210448	http://localhost:9000/files/49a26347453d40b1a9bcb4939f259828.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T134354Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=274727ae9f05c17d42b9926539aa20835d3db56d5ddd8969802131cb1c65147f	2026-02-05 16:13:54.773483
12	2026-02-05 18:09:00.467068	1000000003	16c0013f4c6e4b45acc2c9349c36fc20.pdf	cfe0a067-5009-46b9-9104-091f2d824048	http://localhost:9000/files/16c0013f4c6e4b45acc2c9349c36fc20.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T160900Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=25c6e2ddb8cfd2d7d3023ad8a73e2c2fcebd707b78e71c821a40c8698049b085	2026-02-05 18:39:00.454383
13	2026-02-05 21:02:22.683371	1000000003	ce015c6c9434455582b7325cf97af7c1.pdf	436576ec-c825-4945-9a54-5d1f9c7b6f13	http://localhost:9000/files/ce015c6c9434455582b7325cf97af7c1.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T190222Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=0e937161d957151c0706488bd9e99da0525eb7916287796275989e024497e440	2026-02-05 21:32:22.675025
14	2026-02-05 21:03:28.51449	1000000003	de01c2b0bbff423b8c58761c9ce1b119.pdf	6bf07ef4-5316-429b-8cf4-388efdba2f65	http://localhost:9000/files/de01c2b0bbff423b8c58761c9ce1b119.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T190328Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=7fe18a62261068714f4c13a706144ef06e43484eb07806ce28814187fe0eacbe	2026-02-05 21:33:28.508867
15	2026-02-05 21:03:55.732527	1000000003	6bbf0da71b9144cd859fd20aa9b5a4de.pdf	2b3f7885-5fe2-4efa-8361-d4728f62c128	http://localhost:9000/files/6bbf0da71b9144cd859fd20aa9b5a4de.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260205T190355Z&X-Amz-SignedHeaders=host&X-Amz-Credential=minioadmin%2F20260205%2Faf-south-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=fa006b8ea1665132494289c146793e9cfc79ed8f0f5e0a64795f68652fb72420	2026-02-05 21:33:55.725623
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.transactions (transaction_id, created_at, post_date, account_id, amount, description, dr_or_cr) FROM stdin;
3	2026-02-03 12:00:00	2026-02-03	1000000002	1546.00	Deposit	CR
2	2026-02-02 11:00:00	2026-02-02	1000000001	500.00	Withdrawal	DR
4	2026-02-04 13:00:00	2026-02-04	1000000003	8780.00	Deposit	CR
1	2026-02-01 10:00:00	2026-02-01	1000000001	2000.00	Deposit	CR
5	2026-02-05 14:00:00	2026-02-05	1000000003	2000.00	Withdrawal	DR
6	2026-02-02 15:00:00	2026-02-02	1000000003	9906.00	Deposit	CR
7	2026-02-06 09:15:00	2026-02-06	1000000001	1250.00	ATM Withdrawal	DR
8	2026-02-06 10:30:00	2026-02-06	1000000002	5400.00	Salary Deposit	CR
9	2026-02-07 14:20:00	2026-02-07	1000000001	300.00	Airtime Purchase	DR
10	2026-02-07 16:45:00	2026-02-07	1000000003	12000.00	EFT Transfer	CR
11	2026-02-08 08:00:00	2026-02-08	1000000002	450.00	Grocery Store	DR
12	2026-02-08 11:10:00	2026-02-08	1000000001	2500.00	Cash Deposit	CR
13	2026-02-09 13:05:00	2026-02-09	1000000003	670.00	Fuel Station	DR
14	2026-02-10 15:50:00	2026-02-10	1000000002	850.00	Utility Payment	DR
16	2026-02-12 10:00:00	2026-02-12	1000000003	5000.00	Bonus	CR
15	2026-02-11 12:00:00	2026-02-11	1000000001	7.50	Bank Fee	DR
17	2026-02-03 19:00:06.821337	2026-02-05	1000000003	1235.00	Online Purchase	DR
44	2026-02-03 19:05:07.993147	2026-02-05	1000000003	1235.00	Online Purchase	DR
45	2026-02-05 14:25:09.090156	2026-02-05	1000000003	1235.00	Online Purchase	DR
\.


--
-- Name: audit_logs_audit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.audit_logs_audit_id_seq', 5, true);


--
-- Name: audit_logs_audit_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.audit_logs_audit_id_seq1', 1, false);


--
-- Name: audit_logs_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.audit_logs_seq', 3001, true);


--
-- Name: customer_accounts_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.customer_accounts_seq', 1, false);


--
-- Name: statements_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.statements_seq', 2101, true);


--
-- Name: statements_statement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.statements_statement_id_seq', 15, true);


--
-- Name: transactions_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.transactions_transaction_id_seq', 47, true);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (audit_id);


--
-- Name: customer_accounts customer_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_accounts
    ADD CONSTRAINT customer_accounts_pkey PRIMARY KEY (account_id);


--
-- Name: statements statements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.statements
    ADD CONSTRAINT statements_pkey PRIMARY KEY (statement_id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id);


--
-- Name: statements statements_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.statements
    ADD CONSTRAINT statements_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.customer_accounts(account_id) ON DELETE CASCADE;


--
-- Name: transactions transactions_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.customer_accounts(account_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict QUfHwaMGHbc99CWmEOVOhStkDT0lTEoVPgsuEYbK7CkzAc4fQjhjaleIFoygGgz

